"""
AUTOMATION DASHBOARD — FINAL PRODUCTION RUNNER

Usage:

    python run_report.py leads
    python run_report.py revenue

FLOW:

    Google Sheets
        ↓
    Python memory
        ↓
    Report formatter
        ↓
    Timestamped PNG reports + WhatsApp number file
        ↓
    WhatsApp Web
        ↓
    Number message
        ↓
    CH image
        ↓
    All BDM images
        ↓
    SUCCESS

IMPORTANT:
- No JSON is used.
- Google is extracted directly into Python memory.
- The formatter is called directly.
- The exact report generated by this run is sent.
- No "latest run" lookup is used.
- WhatsApp uses the existing persistent chrome_profile_wa.
- Images use Attach → Photos & videos → native file chooser.
- No captions.
- BDM image count is dynamic.
"""


from pathlib import Path
from datetime import datetime
import argparse
import re
import sys
import time
import traceback


# ======================================================================
# PRODUCTION IMPORTS
# ======================================================================

from google_layer import extract_all
from report_formatter import format_all

from whatsapp_common import (
    TARGET_GROUP,
    start_whatsapp,
    wait_for_whatsapp,
    open_group,
    verify_group,
    send_text,
    send_image,
    close_whatsapp,
)


import config


# ======================================================================
# CONSTANTS
# ======================================================================

RUNNER_NAME = "AUTOMATION DASHBOARD — FINAL PRODUCTION RUNNER"

# Allow WhatsApp time to finish transmitting the final media before Chrome closes.
FINAL_MEDIA_WAIT_SECONDS = 15

RUN_PATTERN = re.compile(
    r"^\d{2}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2}$"
)


# ======================================================================
# LOGGING
# ======================================================================

def log(message=""):
    print(
        f"[{time.strftime('%H:%M:%S')}] {message}",
        flush=True
    )


def banner(title):
    print()
    print("=" * 78)
    print(title)
    print("=" * 78, flush=True)


def section(title):
    print()
    print("-" * 78)
    print(title)
    print("-" * 78, flush=True)


# ======================================================================
# ARGUMENTS
# ======================================================================

def parse_args():

    parser = argparse.ArgumentParser(
        description=(
            "Run the complete Leads/Input or "
            "Revenue/Output automation."
        )
    )

    parser.add_argument(
        "report_type",
        choices=["leads", "revenue"],
        help="Report to generate and send.",
    )

    return parser.parse_args()


# ======================================================================
# VALIDATION
# ======================================================================

def validate_environment():

    section("VALIDATING PRODUCTION ENVIRONMENT")

    required_paths = [
        (
            "Google profile",
            config.GOOGLE_PROFILE_DIR
        ),
        (
            "WhatsApp profile",
            Path(__file__).resolve().parent
            / "chrome_profile_wa"
        ),
        (
            "Report formatter output directory",
            config.SCREENSHOT_DIR
        ),
        (
            "WhatsApp output directory",
            config.WHATSAPP_DIR
        ),
    ]

    for label, path in required_paths:

        if not path.exists():

            raise RuntimeError(
                f"{label} is missing:\n{path}"
            )

        log(f"✓ {label}: {path}")

    log("✓ Production environment validated.")


# ======================================================================
# STEP 1 + STEP 2
# GOOGLE → MEMORY → FORMATTER
# ======================================================================

def build_reports():

    banner("STEP 1 + STEP 2 — GOOGLE → MEMORY → FORMATTER")

    log("Starting Google extraction.")

    started = time.time()

    raw = extract_all()

    extraction_seconds = time.time() - started

    log(
        f"✓ Google extraction completed in "
        f"{extraction_seconds:.2f}s"
    )

    # --------------------------------------------------------------
    # Basic validation before formatting
    # --------------------------------------------------------------

    required_keys = [
        "ch_leads",
        "ch_revenue",
        "bdm_leads",
        "bdm_revenue",
    ]

    for key in required_keys:

        if key not in raw:

            raise RuntimeError(
                f"Google extraction did not return: {key}"
            )

        if not raw[key]:

            raise RuntimeError(
                f"Google extraction returned empty data: {key}"
            )

        log(
            f"✓ {key}: "
            f"{len(raw[key])} rows"
        )

    # --------------------------------------------------------------
    # FORMAT
    # --------------------------------------------------------------

    section("FORMATTING REPORTS")

    format_started = time.time()

    outputs = format_all(raw)

    format_seconds = time.time() - format_started

    log(
        f"✓ Report formatting completed in "
        f"{format_seconds:.2f}s"
    )

    # --------------------------------------------------------------
    # Validate formatter output
    # --------------------------------------------------------------

    timestamp = outputs.get("timestamp")

    lead_dir = Path(
        outputs["lead_dir"]
    )

    revenue_dir = Path(
        outputs["revenue_dir"]
    )

    whatsapp_dir = Path(
        outputs["whatsapp_dir"]
    )

    if not timestamp:
        raise RuntimeError(
            "Formatter did not return a report timestamp."
        )

    if not RUN_PATTERN.match(timestamp):
        raise RuntimeError(
            f"Invalid formatter timestamp: {timestamp}"
        )

    if not lead_dir.exists():
        raise RuntimeError(
            f"Lead report directory was not created:\n"
            f"{lead_dir}"
        )

    if not revenue_dir.exists():
        raise RuntimeError(
            f"Revenue report directory was not created:\n"
            f"{revenue_dir}"
        )

    if not whatsapp_dir.exists():
        raise RuntimeError(
            f"WhatsApp output directory was not created:\n"
            f"{whatsapp_dir}"
        )

    log(f"✓ Report run: {timestamp}")
    log(f"✓ Leads directory: {lead_dir}")
    log(f"✓ Revenue directory: {revenue_dir}")

    log(
        f"✓ BDM Leads images: "
        f"{outputs['bdm_lead_images']}"
    )

    log(
        f"✓ BDM Revenue images: "
        f"{outputs['bdm_revenue_images']}"
    )

    return outputs


# ======================================================================
# IMAGE ORDER
# ======================================================================

def bdm_number(path, report_type):

    if report_type == "leads":

        pattern = r"BDM_leads_(\d+)_"

    else:

        pattern = r"BDM_revenue_(\d+)_"

    match = re.search(
        pattern,
        path.name,
        re.IGNORECASE
    )

    if match:

        return int(
            match.group(1)
        )

    return 999999


def find_report_images(run_dir, report_type):

    run_dir = Path(run_dir)

    ch_dir = run_dir / "CH"
    bdm_dir = run_dir / "BDM"

    if not ch_dir.exists():

        raise RuntimeError(
            f"CH report directory missing:\n{ch_dir}"
        )

    if not bdm_dir.exists():

        raise RuntimeError(
            f"BDM report directory missing:\n{bdm_dir}"
        )

    ch_images = sorted(
        ch_dir.glob("*.png")
    )

    bdm_images = sorted(
        bdm_dir.glob("*.png"),
        key=lambda path: (
            bdm_number(path, report_type),
            path.name,
        )
    )

    if not ch_images:

        raise RuntimeError(
            f"No CH {report_type} report image found."
        )

    if not bdm_images:

        raise RuntimeError(
            f"No BDM {report_type} report images found."
        )

    images = (
        ch_images
        +
        bdm_images
    )

    return images


# ======================================================================
# WHATSAPP MESSAGE
# ======================================================================

def load_whatsapp_message(
    whatsapp_dir,
    report_type
):

    if report_type == "leads":

        filename = "leads_numbers.txt"

    else:

        filename = "revenue_numbers.txt"

    message_file = (
        Path(whatsapp_dir)
        /
        filename
    )

    if not message_file.exists():

        raise RuntimeError(
            f"WhatsApp number message is missing:\n"
            f"{message_file}"
        )

    message = (
        message_file
        .read_text(
            encoding="utf-8"
        )
        .strip()
    )

    if not message:

        raise RuntimeError(
            f"WhatsApp number message is empty:\n"
            f"{message_file}"
        )

    return message, message_file


# ======================================================================
# STEP 3 — WHATSAPP
# ======================================================================

def send_report(
    report_type,
    outputs
):

    banner(
        "STEP 3 — WHATSAPP DELIVERY"
    )

    timestamp = outputs["timestamp"]

    if report_type == "leads":

        run_dir = Path(
            outputs["lead_dir"]
        )

        title = "INPUT / LEADS"

    else:

        run_dir = Path(
            outputs["revenue_dir"]
        )

        title = "OUTPUT / REVENUE"

    message, message_file = (
        load_whatsapp_message(
            outputs["whatsapp_dir"],
            report_type
        )
    )

    images = find_report_images(
        run_dir,
        report_type
    )

    # --------------------------------------------------------------
    # Print exact delivery plan BEFORE WhatsApp starts.
    # --------------------------------------------------------------

    section(
        f"DELIVERY PLAN — {title}"
    )

    print(
        f"Target group : {TARGET_GROUP}"
    )

    print(
        f"Report run   : {timestamp}"
    )

    print(
        f"Number file  : {message_file}"
    )

    print(
        f"Total images : {len(images)}"
    )

    print()

    for index, image in enumerate(
        images,
        1
    ):

        print(
            f"{index}. {image.name}"
        )

    # --------------------------------------------------------------
    # START WHATSAPP
    # --------------------------------------------------------------

    pw = None
    context = None

    try:

        pw, context, page = (
            start_whatsapp()
        )

        wait_for_whatsapp(
            page
        )

        open_group(
            page,
            TARGET_GROUP
        )

        verify_group(
            page,
            TARGET_GROUP
        )

        # ----------------------------------------------------------
        # NUMBER MESSAGE
        # ----------------------------------------------------------

        section(
            "SENDING NUMBER MESSAGE"
        )

        send_text(
            page,
            message
        )

        log(
            "✓ Number message sent."
        )

        time.sleep(2)

        # ----------------------------------------------------------
        # IMAGES
        # ----------------------------------------------------------

        banner(
            f"SENDING {title}"
        )

        for index, image in enumerate(
            images,
            1
        ):

            log(
                f"[{index}/{len(images)}] "
                f"Sending {image.name}"
            )

            send_image(
                page,
                image
            )

            log(
                f"✓ [{index}/{len(images)}] sent"
            )

            if index < len(images):

                time.sleep(4)

        # ----------------------------------------------------------
        # FINAL MEDIA TRANSMISSION BUFFER
        # ----------------------------------------------------------
        # Clicking WhatsApp's Send button does not guarantee that the
        # media has finished uploading/transmitting. Give the final
        # image time to leave the browser before cleanup closes Chrome.
        log(
            f"Waiting {FINAL_MEDIA_WAIT_SECONDS}s for final media transmission..."
        )

        time.sleep(
            FINAL_MEDIA_WAIT_SECONDS
        )

        log(
            "✓ Final media transmission wait completed."
        )

        # ----------------------------------------------------------
        # SUCCESS
        # ----------------------------------------------------------

        banner(
            f"{title} DELIVERY — PASSED"
        )

        print()
        print(
            "✓ Number message sent"
        )

        print(
            "✓ CH report sent"
        )

        print(
            f"✓ {len(images) - 1} BDM report image(s) sent"
        )

        print(
            f"✓ Total images: {len(images)}"
        )

        print(
            f"✓ Run: {timestamp}"
        )

        return 0

    finally:

        if pw and context:

            try:

                close_whatsapp(
                    pw,
                    context
                )

            except Exception as error:

                log(
                    f"WARNING: WhatsApp cleanup issue: "
                    f"{error}"
                )


# ======================================================================
# MAIN
# ======================================================================

def main():

    args = parse_args()

    report_type = args.report_type

    banner(
        RUNNER_NAME
    )

    print()
    print(
        f"MODE: {report_type.upper()}"
    )

    print(
        f"Target group: {TARGET_GROUP}"
    )

    print()

    total_started = time.time()

    try:

        # ==========================================================
        # ENVIRONMENT
        # ==========================================================

        validate_environment()

        # ==========================================================
        # GOOGLE → MEMORY → FORMATTER
        # ==========================================================

        outputs = build_reports()

        # ==========================================================
        # WHATSAPP
        # ==========================================================

        send_report(
            report_type,
            outputs
        )

        # ==========================================================
        # FINAL SUCCESS
        # ==========================================================

        total_seconds = (
            time.time()
            -
            total_started
        )

        banner(
            "AUTOMATION RUN — PASSED"
        )

        print()
        print(
            f"Report type : {report_type.upper()}"
        )

        print(
            f"Run         : {outputs['timestamp']}"
        )

        print(
            f"Total time  : {total_seconds:.2f}s"
        )

        print()
        print(
            "✓ Google extraction"
        )

        print(
            "✓ Direct-memory processing"
        )

        print(
            "✓ Report formatting"
        )

        print(
            "✓ WhatsApp number message"
        )

        print(
            "✓ CH report"
        )

        print(
            "✓ All BDM reports"
        )

        print()
        print(
            "✓ COMPLETE AUTOMATION SUCCESS"
        )

        return 0

    except Exception as error:

        total_seconds = (
            time.time()
            -
            total_started
        )

        banner(
            "AUTOMATION RUN — FAILED"
        )

        print()
        print(
            f"Report type : {report_type.upper()}"
        )

        print(
            f"Runtime     : {total_seconds:.2f}s"
        )

        print()
        print(
            f"ERROR: {error}"
        )

        print()
        print(
            "TRACEBACK"
        )

        traceback.print_exc()

        return 1


if __name__ == "__main__":

    raise SystemExit(
        main()
    )